### ISSUE TITLE
waiting for your update

### ISSUE THREAD

**Issue by xxlxxl123** [Urkman/s3xy-watch-for-tesla#2]
that's most important is
 Siri and watch keyless,that's amazing . Thanks

**Comment by Urkman** [comment]
Siri will come with the next update...
Keyless in case of starting your Tesla with a PIN will also come (hopefully) with the next update
Bluetooth support will take some time, but is planned...

**Comment by xxlxxl123** [comment]
nice

**Comment by xxlxxl123** [comment]
![image](https://user-images.githubusercontent.com/27720625/217434917-7eac60f9-24ca-480a-b619-d816107fe881.png)

whats is this ？

**Comment by Urkman** [comment]
This error occurs, when there is a problem connection the Tesla API...
Then just try again...
But sometimes, the API is just not available for some seconds or minutes...
