### ISSUE TITLE
Climate control 

### ISSUE THREAD

**Issue by jj2dogs** [Urkman/s3xy-watch-for-tesla#3]
Hi all. 
When submitting a climate control i get this issue. 
Thank you for any help. 
![98309DBA-6059-4DFA-BDA0-88F6F585BAEA](https://user-images.githubusercontent.com/69296580/218271045-d51f9e97-c10b-403a-b642-ea58089f7426.jpeg)

**Comment by Urkman** [comment]
Is it possible, that you tried to turn on the steering wheel heater?
If so, it is not possible to turn it on without enabling the climate...

**Comment by jj2dogs** [comment]
Hi. Thanks for the quick reply.  It was turning on the seat heater. But yeah. Tried turning on the climate on first and than seat heater and that worked. So all good. Need to remember to do it like that even the tesla app does it automatically.  Also a tip for future update. After sending a command it would be nice if the apple watch refreshed on it’s own to reflect the status.  Thx for helping.
