### ISSUE TITLE
Fahrzeug Bild fehlt

### ISSUE THREAD

**Issue by Xoffroad** [Urkman/s3xy-watch-for-tesla#4]
Seit heute fehlt das Fahrzeugbild. Es wurde kein eigenes Bild gesetzt sondern der Standard beibehalten.

![CD0D279A-88C8-4F80-A0B3-AB305662C563](https://user-images.githubusercontent.com/65235705/225727693-b1c029cc-5909-4bad-8f53-4aeb4f1896c4.jpeg)

**Comment by Urkman** [comment]
Sorry, für die späte Rückmeldung. Hat sich das Problem mittlerweile erledigt?

**Comment by Xoffroad** [comment]
Sollte seit dem vorletzten Update behoben sein.
